### PR TITLE
Script to compare two tags.

### PR DESCRIPTION
**Pull request by chiarazampolli**
There is also the script runCompareAllHistos.sh which was written to
be integrated in the RelVal, this is what I use.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
This is just a new script for Release Validation. I will merge it.

**Comment by fprino** [comment]
Hi,

with this version of the script there are some TDirectories of QAresults.root that are not checked, e.g.
Vertex_Performance, SPD_Performance, T0_Performance and many others, sice you run only on TDitrectories whose name contains one of these strings: TPC TOF ITS TRD CaloQA_default CaloQA_trigEMC.
An option could be to call CompareAllHistos.C with \\"\\" as third argument, so that all TDirectories in the root file are checked.

Ciao, Francesco

**Comment by chiarazampolli** [comment]
Ciao Francesco,

Thanks! I will check to modify the script, but usually this is what I check (ITS, TRD, TOF, TPC, AOD, EMCAL) in the RelVal... The script as it is is also creating an output log file per directory, for the sake of simplicity to isolate them. I will see if I can make it like this in a smart way.

Cheers,

Chiara

**Comment by fprino** [comment]
Hi,

OK. Just keep in mind that with the string selection "ITS" you are not checks all the ITS plots, because the  subdetector QA has directories named SPD_Performance, SDD_Performance...
A possibility could be to add SDD SPD SSD and ertex to the list of directories in the loop.

II do not see issues in having a single file with the output of all directories, but if you wish I can modify the macro such that it writes the output in different files grouped per detector.

Cheers, Francesco

**Pull request merged**
