### PR TITLE
Added casting

### PR DESCRIPTION
**Pull request by alcaliva**

### CODE REVIEW

**Comment by alcaliva** [comment]
I hope it is fine now. I cleaned up my commit and I get no conflict with the base branch

**Comment by gconesab** [comment]
No still conflicts, one should not have the list of previous commits that were already merged.
Have you done git pull --rebase?

**Comment by alcaliva** [comment]
I get the following, which I don't know how to fix. 
Can you help me?

git pull --rebase https://github.com/alisw/AliDPG
From https://github.com/alisw/AliDPG
 * branch            HEAD       -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: pythia8 monash2013 with leading particle
Using index info to reconstruct a base tree...
.git/rebase-apply/patch:8: trailing whitespace.
  
.git/rebase-apply/patch:10: trailing whitespace.
  
.git/rebase-apply/patch:13: trailing whitespace.
    
.git/rebase-apply/patch:19: trailing whitespace.
  
warning: 4 lines add whitespace errors.
Falling back to patching base and 3-way merge...
CONFLICT (add/add): Merge conflict in MC/CustomGenerators/PWGLF/Pythia8_Monash2013_TriggerParticle.C
Auto-merging MC/CustomGenerators/PWGLF/Pythia8_Monash2013_TriggerParticle.C
error: Failed to merge in the changes.
Patch failed at 0001 pythia8 monash2013 with leading particle
hint: Use 'git am --show-current-patch' to see the failed patch
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
albertocaliva@Albertos-MBP AliDPG %

**Comment by gconesab** [comment]
Hi, just abort as it suggests "git rebase --abort" and then try
git reset --hard upstream/master
git push -f origin
as suggests 
https://alisw.github.io/git-tutorial/

**Comment by alcaliva** [comment]
Hi Gustavo,
is this still conflicting?

**Comment by gconesab** [comment]
Now it  seems ok

**Comment by alcaliva** [comment]
Hi Gustavo,

I have tested the generator and it works. We would need it to run a MC production that we are about to request. When is the next DPG release expected to be available?

**Comment by gconesab** [comment]
If I am not mistaken, this was included in the last tag

**Pull request merged**
