### PR TITLE
Adding creation of AliGenCocktail

### PR DESCRIPTION
**Pull request by arossi81**
This is a fix for a further line that was forgotten when moving this piece of code to CustomGenerators.

### CODE REVIEW

**Comment by miweberSMI** [comment]
Ciao @arossi81,

did you test this macro after your change? I get the error message "F-AliGenCocktail::Generate(): No Collision Geometry Provided", probably connected to the fact that HIJING (which usually comes then with the collision geometry parameters) is missing in the macro?
I would add two lines after the cocktail creation:
- AliGenerator   *hij   = GeneratorHijing();
- ctl->AddGenerator(hij,  "Hijing", 1.);

Cheers,
Michael

**Comment by arossi81** [comment]
Hi @miweberSMI ,
yes, sorry! I did not test the macro since I thought it was a trivial addition but definitely I forgot to add the two lines you mention. They must be there. 
Cheers,
Andrea

**Comment by miweberSMI** [comment]
Ciao @arossi81,

now it is working fine, thanks for the quick modification. I am merging this pull request and port it to the production branches...

Cheers,
Michael

**Comment by arossi81** [comment]
Ciao @miweberSMI ,
thanks!
Andrea

**Pull request merged**
