### PR TITLE
 Adding new argument to define G4 Physics List

### PR DESCRIPTION
**Pull request by chiarazampolli**
There is again the same commit for ESDfriends of yesterday, I don't know why, but it should be harmless (not changing anything).

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Dear @miweberSMI , @fprino , @catalinristea ,
Here the commit to add a configuration parameter for the G4 physics list. Can you please check? 
For some reason (I don't know why...) there is again my commit from yesterday too... 
Chiara

**Comment by catalinristea** [comment]
Ciao Chiara,

The G4 changes look good to me, thanks.

Yours,
Catalin.

**Comment by chiarazampolli** [comment]
Merging now... I hope it is fine also for @miweberSMI . 

Chiara

**Comment by miweberSMI** [comment]
Hi @chiarazampolli,

looks good to me (sorry for being late), I did not test it now though...

Cheers,
Michael

**Comment by chiarazampolli** [comment]
Ciao Michael, 

I also did not test it, so let's cross our fingers :-)

Chiara

**Pull request merged**
