### PR TITLE
New custom generator for PWGDQ-LMee: HF dielectron triggered Pythia

### PR DESCRIPTION
**Pull request by miweberSMI**

### CODE REVIEW

**Comment by preghenella** [comment]
I tested the pull request and it works.
Waiting for comments from PWG conveners before merging to the master.

**Comment by iarsene** [comment]
+1

**Comment by preghenella** [comment]
I'm not sure I understand the comment from @iarsene, but I take it is and positive one.

**Comment by iarsene** [comment]
Hi Roberto, you refer to my "+1" ? I also commented on the corresponding JIRA ticket. You said there that the PWG conveners should approve the pull request. So i thought that "+1" means i approve. I only forked today AliDPG and I do not actually know what is the chain of approvals here... whether its the same as in AliPhysics ...

**Comment by preghenella** [comment]
yes, sorry I missed the comment on JIRA.
There is still not an official chain, at least not until everything will be in place and properly advertised. Thanks!

**Comment by iarsene** [comment]
Ok, then I should just comment in words on the pull requests, and let you do the "+1" and "+test"

**Comment by preghenella** [comment]
Soon we will have something like AliRoot and you will be able to do it yourself :-)

Roberto Preghenella
http://about.me/preghenella

**Pull request merged**
