### PR TITLE
New MC generator for eta prime studies

### PR DESCRIPTION
**Pull request by fkellere**

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @fkellere,

I just tried to test this new generator macro, but I guess you have to commit also the changes for the forced decay first to ALIROOT?

Thanks and cheers,
Michael

**Comment by fkellere** [comment]
Hi @miweberSMI, yes thats already done. Pull request for AliRoot is out, but not yet approved.

**Comment by miweberSMI** [comment]
Hi @fkellere,

OK, understood. Could you point me to the PR?

Thanks and cheers,
Michael

**Comment by fkellere** [comment]
https://github.com/alisw/AliRoot/pull/966
@miweberSMI

**Comment by fkellere** [comment]
Hi @miweberSMI,
the AliRoot pull request was finally approved and merged. Now the new generator should work as intended. Could you have a look again?
Thanks and cheers,
Fabian

**Comment by miweberSMI** [comment]
Hi @fkellere, 
I have seen that and will do the test as soon as possible.
Cheers,
Michael

**Comment by miweberSMI** [comment]
Hi @fkellere, all,

I tested this macro with the recent AliRoot master and the full simulation chain is running and yields in AODs that contain tracks. Before merging, I would like to ask GA conveners for their confirmation that the macro should go with this name in the GA folder?
Also, is there already a JIRA ticket for a production and/or is this discussed in the Physics Board? Or is it for private use only so far?

Thanks and cheers,
Michael

**Comment by fkellere** [comment]
Hi @miweberSMI,
this is intended to be used for larger productions later on. However there is no JIRA ticket or discussion yet.
Cheers,
Fabian

**Comment by miweberSMI** [comment]
Hi @fkellere,

OK, thanks for clarification. Then I am still waiting for GA conveners to give their green light (if you want you can ping them again).

Cheers,
Michael

**Comment by FriederikeBock** [comment]
Hi @fkellere ,
could we also include the decay of the eta' to eta pi+pi- in this commit please (branching 50:50) so that we have everything ready for the full production?
Regards,
Friederike

**Comment by fkellere** [comment]
Hi @FriederikeBock ,
I am working on it, but this can be done by only changing the implementation of the kEtaPrime decay in AliRoot. As far as I can see, no changes to the generator need to be made so there should be no problem with just accepting this pull request and then waiting for the AliRoot changes to be accepted as well.
Cheers,
Fabian

**Comment by fkellere** [comment]
Hi @FriederikeBock ,
the pull request for the new decayer configs in AliRoot is now out at https://github.com/alisw/AliRoot/pull/978. 
Greetings,
Fabian

**Comment by FriederikeBock** [comment]
Hi @fkellere,
then this commit is fine from the GA side.
Regards,
Friederike

**Comment by miweberSMI** [comment]
OK, I will then wait for the new ALIROOT tag and test again. If OK, I will merge it...

**Comment by miweberSMI** [comment]
Dear all,

I tested the updated macro once more (with updated AliRoot master) and it doesn't show any problems with running (I did not check the results). Since GA conveners already agreed, I am merging it to the AliDPG master.

Cheers,
Michael

**Pull request merged**
