### PR TITLE
Consolidate HF PbPb Hijing generators into one macro

### PR DESCRIPTION
**Pull request by jezwilkinson**
This commit:
- moves the embedding functionality from Hijing_HF001_EmbedB.C into Hijing_HF001.C
- removes now-obsolete HF001_EmbedA and HF001_EmbedB macros (Hijing_HF001.C now covers all cases whether embedding is on or off)

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Looks ok to me. @arossi81 , @agrelli, @xcheung, can you confirm that we can merge?

Thanks!

Chiara

**Comment by agrelli** [comment]
Ciao @chiarazampolli 

looks ok to me. I guess @jezwilkinson did a fast test

Alessandro

**Comment by chiarazampolli** [comment]
Hello,

@fprino , @miweberSMI , I could not spot any issues, so is it ok to merge? Maybe you also want to have a look (I don't know if @jezwilkinson tested the changes, since he did not reply yet). 

Chiara

**Comment by fprino** [comment]
Hi,

I gave a quick look at the code modifications and they look OK to me.

Cheers, Francesco

**Comment by chiarazampolli** [comment]
Merging.

Chiara

**Pull request merged**
