### PR TITLE
Custom Generator for J/psi injected HIJING for PbPb2018

### PR DESCRIPTION
**Pull request by mkkohler**
HIJING + J/psi, non-prompt is generated by EvtGen.
Generator follows previous version (HIJING_Jpsiee001.C), but with a natural pT shape.

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @mkkohler, all,

I tested both in normal and in embedded (+ signal filtering mode) and bit are working fine. Of course, I didn't test the output but I assume that is OK. Perhaps the conveners can give their formal approval of the macro, then I will merge and we could ask for a new tag.

Thanks and cheers,
Michael

**Comment by tdahms** [comment]
Hi,

this looks good to me. DQ approves.

Best,
Torsten

**Comment by miweberSMI** [comment]
Hi @tdahms,

thanks for confirmation, I understood from @mkkohler (on https://alice.its.cern.ch/jira/browse/ALIROOT-8251) that he still would like to implement centrality dependent injection before merging, so I will still wait.

Cheers,
Michael

**Comment by miweberSMI** [comment]
Hi @mkkohler , @ffionda, all,

do I understand correctly that this PR is overwritten by https://github.com/alisw/AliDPG/pull/268? Which would mean I close that one and only approve the other one (268)?

Thanks for clarification,
Michael

**Comment by miweberSMI** [comment]
Dear all,

I am closing this PR since it is replaced by #266 (see comment by @ffionda).

Cheers,
Michael

**Pull request closed without merging**
