### PR TITLE
Bug fix 

### PR DESCRIPTION
**Pull request by alcaliva**

### CODE REVIEW

**Comment by gconesab** [comment]
I think you need to open an new PR, there are conflicts. 
Why do you need to put the generator into a cocktail?
Gustavo

**Comment by alcaliva** [comment]
I would need to generate pythia8 events with a trigger particle having a pt>5 GeV. 
Is there a better way?

**Comment by gconesab** [comment]
In the same way you where doing before this commit. I do not understand the new approach. Maybe just you need the casting to AliGenPythiaPlus.

Gustavo

**Comment by alcaliva** [comment]
OK, will try. Thanks

**Pull request closed without merging**
