### PR TITLE
Fixes for root5/root6 compatibility

### PR DESCRIPTION
**Pull request by shahor02**
+ call OCDBConfigCustom with rec/sim flag

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello Ruben,

According to github, your PR has conflicts. Should I check them, or you want to have a look?

Cheers,

Chiara

**Comment by shahor02** [comment]
Hi Chiara,
I will check after the lunch
Cheers
  Ruben

On Mar 14, 2018 11:25, chiarazampolli <notifications@github.com> wrote:

Hello Ruben,

According to github, your PR has conflicts. Should I check them, or you want to have a look?

Cheers,

Chiara

**Comment by shahor02** [comment]
Hi,
The OCDB snapshot generation was always done with kOCDBDefault only, I've added to dpgsim.sh new option --ocdbCustom (w/o arguments) to pass kOCDBCustom flag to CreateSnapshot macro.
Cheers,
 Ruben

**Comment by chiarazampolli** [comment]
Hi Ruben,

Done!

Chiara

**Pull request merged**
