### PR TITLE
Config and specific decay table for ITS3 production.

### PR DESCRIPTION
**Pull request by arossi81**

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @arossi81,

thanks for the commit. Is this the version that we are currently testing on the GRID?

Cheers,
Michael

**Comment by arossi81** [comment]
yes. I do not consider it final, but I'd prefer to have it committed anyway, if possible

**Comment by miweberSMI** [comment]
Hi @arossi81,

OK, then I will merge it as soon as the tests are successful...

Cheers,
Michael

**Comment by miweberSMI** [comment]
Dear @arossi81, 

do we expect a new config in the next days here? Otherwise we would tag now and then we can include this macro later...

Cheers,
Michael

**Comment by arossi81** [comment]
Hi @miweberSMI ,
I guess that we will have a new Config in the next days.
Cheers,
Andrea

**Comment by chiarazampolli** [comment]
Ciao @arossi81 , 

I am for now closing this PR, since the config is still under test. Please, open a new one when ready.
Thanks!
Chiara

**Pull request closed without merging**
