### PR TITLE
Added EMCAL reshuffle configuration

### PR DESCRIPTION
**Pull request by catalinristea**
Ciao @chiarazampolli , @fprino 

Here is the final EMCAL reshuffle configuration. 
It's just running in grid and jobs seem to do just fine with it.
Thanks!

Yours,
Catalin.

### CODE REVIEW

**Comment by fprino** [comment]
Hi,
we can  merge this change.
Before tagging AliDPG we have to make a decision on the AD modification.
Maybe the fastest thing is to revert that commit, while we wait for the AD feedack on the 2 solutions that I proposed in that PR.

Cheers, Francesco

**Comment by chiarazampolli** [comment]
Ciao Francesco,
Yes, we should better revert that commit first (I missed that it was already merged).
Cheers,
Chiara

**Comment by chiarazampolli** [comment]
PS: anyway, this is not urgent, as the reshuffling is ongoing with the tarball. But the tag is needed for the nuclei MC.

**Comment by fprino** [comment]
Hi,
I reverted the PR for AD.
Cheers, Francesco

**Comment by chiarazampolli** [comment]
I am merging this... I think we forgot :)

**Pull request merged**
