### PR TITLE
Initial commit for unified main/re-filtering AOD macro

### PR DESCRIPTION
**Pull request by catalinristea**
Ciao @chiarazampolli , @fprino 

Here is the initial commit for unified main/re-filtering AOD macro.
I have tested it also in production, for a GP configuration. 
Please have a look and let me know if there are any issues.
Thanks!

Yours,
Catalin.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Ciao Catalin,

To me it looks ok. Please, go on with the merging to master.

Thanks!!

Chiara

**Comment by fprino** [comment]
Hi,

I also had a look and I agree to merge it.
Thanks!

Ciao, Francesco

**Comment by catalinristea** [comment]
Dear all,

Thanks a lot, now I have the opportunity to move one more step forward for my github knowledge :)

Yours,
Catalin.

**Comment by catalinristea** [comment]
Hi,

I'll start by reverting this pull request and try to redo it w/o only with the proper commit.
Thanks!

Yours,
Catalin.

**Comment by chiarazampolli** [comment]
Hi Catalin,

Thanks, but really, it was not needed... The commit was fine as it was. 

Cheers,

Chiara

**Pull request merged**
