### PR TITLE
Add generator Hijing_Nuclex005

### PR DESCRIPTION
**Pull request by lbariogl**
Added generator with the injection of Ps(2100), Ps(2500), d*(2380) + CC

### CODE REVIEW

**Comment by preghenella** [comment]
Thanks Luca for your pull request and the code updates.
The changes in GeneratorConfig.C are ok with me and the new custom Hijing_Nuclex005.C is also well prepared. 

Even though PWG conveners were not informed about the latest changes in MC configuration strategy in AliDPG (via pull requests), I will assign them to this ticket for their approval.

**Comment by preghenella** [comment]
uhm, no I cannot assign this ticket to PWG conveners, apparently.
Never mind, for the time being I keep it open and I will take care of it next week.

**Comment by preghenella** [comment]
@dberzano , who are the people to whom one can assign pull requests? Currently the list includes very few people. Thanks

**Comment by dbobulsk** [comment]
Thanks @lbariogl for adding Ps states into the generator cocktail. However, I spotted small bug - on the line 1013 in the changed GeneratorConfig.C a comma is missing after the "Hyper-Helium-4".

**Comment by lbariogl** [comment]
Thanks @dbobulsk, I fixed it.

**Comment by dbobulsk** [comment]
Dear conveners, I added CG Dpmjet_Nuclex001 generator with Ps(2100), Ps(2500) and d*(2380). Since it is the first DMJET Nuclex generator, should we have a structure that reflects the one of already used nuclex generators (like Nuclex_Hijing)? Should we align these two things?

**Comment by preghenella** [comment]
Dear @lbariogl,

I the configurations and the content of your pull request
* Hijing_Nuclex005
* Dpmjet_Nuclex001
with AliPhysics/v5-09-01-01-1.

They both fail with segmentation violation. There must be something specifici in the configuration that needs a more recent AliRoot version (I noticed some commits from Lee regarding the d*).
Can you please comment which AliRoot tag is required for this pull request to be successful?

**Comment by lbariogl** [comment]
Dear @preghenella,

the needed code is not present in this version of AliRoot.
It will be present in v5-09-02

**Comment by preghenella** [comment]
Ok, can you please add a comment about the first AliRoot version to be used in the corresponding files? Thanks 

Roberto Preghenella
http://about.me/preghenella

**Comment by lbariogl** [comment]
Dear @preghenella,

I added in the two generators files the version requirements.
Thanks!

**Comment by preghenella** [comment]
Great! Thank you very much.

**Comment by preghenella** [comment]
Dpmjet_Nuclex001 configuration does not pass the test with AliPhysics/v5-09-02-01-1.
Please, check the configuration, test it and update whatever is needed (also recommended AliRoot in case).

**Comment by preghenella** [comment]
Hijing_Nuclex005 seems to be working.

**Comment by lbariogl** [comment]
Dear @preghenella 
I have removed Dpmjet_Nuclex001.
Thank you

**Comment by preghenella** [comment]
I'm not sure what happened. At some points this pull request was fine, but now I still see the DPMJET file there. Perhaps I did something wrong (even though I'm not sure what), apologies in case. @lbariogl, can you try to remove it again? Thanks

**Comment by preghenella** [comment]
Now all looks fine, perhaps GitHub is making me fool...

**Comment by lbariogl** [comment]
Thank you @preghenella 
there has been a problem indeed: after my fiirst commit of this mornign you pushed to my repository

screen shot 2017-03-30 at 10 05 56

After that I fixed it removing Dpmjet agin.

Thank you again

**Comment by preghenella** [comment]
sorry for that... it was not supposed to happen and I must have reversed by mistake the directions (still weird that GitHub allows me to push to your repo).

**Comment by lbarnby** [comment]
Still trying to get to grips with this git system so excuse me if I am confused. Is the DPMJET nuclei injection not going ahead? I don't see it in the 'Files changed'? Was the problem that was fixed the removal of it from the request and not fixing any problem with the code?

**Comment by dbobulsk** [comment]
Hi @lbarnby, yes, at the end we decided to proceed with EPOS, not with DPMJET which had some unresolved issues. You can find new CG Epos_Nuclex005 for the injection of d* and Ps in the file with PWGLF Custom Generators (and you can find the pull request here https://github.com/alisw/AliDPG/pull/8).

**Comment by preghenella** [comment]
dear @lbariogl ,

I found and solved the issue with the Dpmjet.
It the configuration is needed you can proceed with a new pull request.

Roberto

**Pull request merged**
