### PR TITLE
Move Resonance p-Pb generator to AliGenParam

### PR DESCRIPTION
**Pull request by mpuccio**
Hi @miweberSMI , @aknospe,

could you please check that this PR does what is required by [this production](https://alice.its.cern.ch/jira/browse/ALIROOT-7609)?

Thanks a lot,
Cheers,
Max

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @mpuccio,

thanks a lot, I am testing it right now.
One thing I was wondering, is if we should move the "AliGenParam" part to "GeneratorConfig.C"? @fprino, @chiarazampolli, what do you think?

Cheers,
Michael

**Comment by fprino** [comment]
Hi,
I guess you refer to the function GeneratorParam.
I agree that it would be better to have it in GeneratorConfig.C becassue it coul be called by other CustomGenerators.

Cheers, Francesco

**Comment by mpuccio** [comment]
Yes, that starts to be everywhere. If you want I can amend this PR cleaning up also the other LF generators.
Cheers,
Max

**Comment by miweberSMI** [comment]
Hi @mpuccio,

that would be great.
When moving it to GeneratorConfig.C, it woudl be good to add also a comment (similar to the Injector):
  "comment = comment.Append(Form(" | injected (pdg=%d, %d particles)", pdg, ninj));" or similar...

Thanks and cheers,
Michael

**Comment by aknospe** [comment]
It looks OK from our side.

**Comment by mpuccio** [comment]
Hi @fprino , @miweberSMI ,

GeneratorParam has been moved to the GeneratorConfig.C macro. Please check that I did not destroy anything :)

Cheers!
Max

**Comment by miweberSMI** [comment]
Hi @Max, all,

I tested the three macros that contain GeneratorParam and all of them run fine with the latest AliRoot/AliPhysics master. I will merge this pull request and port to production branches.

Thanks a lot for taking care of this and cheers,
Michael

**Comment by akalweit** [comment]
Already committed, but looks okay in any case.

**Pull request merged**
