### PR TITLE
Using new AliGenCocktail mode for RsnNcl production

### PR DESCRIPTION
**Pull request by mpuccio**
This PR adapts the RsnNcl generator to the new AliGenCocktail mode that allows the user to use a single generator on top of a background event choosing randomly from the list of the generators. This new mode, as well as this generator, will be working with AliRoot master as soon as [this pr](https://github.com/alisw/AliRoot/pull/512) will be merged.

Cheers,
Max

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @mpuccio,

I will wait for the updated AliRoot master to test it. Do you plan to use this generator also for "old" aliroot versions, i.e. v5-08-13 patches?

Cheers,
Michael

**Comment by mpuccio** [comment]
Hi @miweberSMI,

no, it won’t be possible unfortunately as it requires a new method of the AliGenCocktail.
Thanks a lot!!
Cheers,
Max

**Comment by mpuccio** [comment]
Hi @miweberSMI ,
did you have the chance to check if this generator works fine?
Cheers!
Max

**Comment by miweberSMI** [comment]
Hi @mpuccio,

I think there is a small bug. Shouldn't it be 18 instead of 16?
Apart from that it is running fine...

Cheers,
Michael

**Comment by mpuccio** [comment]
Hi @miweberSMI ,
thanks a lot for checking inside the code, indeed it was a bug and it is strange that CINT does not complain about initialisation of an array of size 16 with something of size 18...
Anyway, I fixed it now!

Thanks a lot!
Max

**Comment by miweberSMI** [comment]
Hi @mpuccio,

thanks a lot for the quick update. I am merging this PR.

Cheers,
Michael

**Pull request merged**
