### PR TITLE
Ideal vertex in case of generator only production + adding new HF cus…

### PR DESCRIPTION
**Pull request by miweberSMI**
…tom macro

### CODE REVIEW

**Comment by miweberSMI** [comment]
Dear @afestant, @chiarazampolli, @fprino, 

I finally managed (lack of time so far, apologies) to modify the central macros to distinguish two cases: ideal vertex (0,0,0) in case of generator only productions and CDB vertex if full simulation. It is not beautiful, but it works. What do you think? 
In addition, I committed also the custom macro. @afestant is something else missing (other macros that were modified)?

Cheers,
Michael

**Comment by afestant** [comment]
Dear @miweberSMI,

thanks a lot for the commit. I didn't even modify the SimulationConfig.C because in case you set "--GeneratorOnly", sim.SetRunGeneratorOnly(kTRUE); is called and AliSimulation::RunGeneratorOnly doesn't use the vertex from the OCDB if I have understood correctly. In any case, the commit looks fine to me.

Thanks again
Cheers,
Andrea

**Comment by miweberSMI** [comment]
Hi @afestant,

good point! I reverted the changes in SimulationConfig.C since it is not needed.
Should we merge it now, @chiarazampolli, @fprino? Then we could do some testing on the LS4+ production once a new tag is there.

Thanks and cheers,
Michael

**Comment by chiarazampolli** [comment]
Ciao Michael,
Yes, for me we can merge.
Cheers,
Chiara

**Comment by miweberSMI** [comment]
OK, thanks. I will merge then.

**Pull request merged**
