### PR TITLE
Fix merge.C errors in ROOT 6

### PR DESCRIPTION
**Pull request by dberzano**
* Fix variable declared twice
* Fix ambiguous call to `StartAnalysis()`

### CODE REVIEW

**Comment by dberzano** [comment]
@fprino @chiarazampolli merging this, it's important for the release validation (I am more and more impressed by how ROOT 5 never reported any problem!)

**Comment by chiarazampolli** [comment]
Ciao Dario,

Thanks! I don't know why I did not see this error when testing locally the changes for ROOT6. Anyway, very good that you fixed it! Did you also tried it with ROOT5? Just to be sure that we don't break prodcutions (as we now tag from master, as you know).

Cheers,

Chiara

**Comment by dberzano** [comment]
Yes, in any case bear in mind that the release validation also tests AliDPG master, so we would spot problems immediately.

**Comment by chiarazampolli** [comment]
I know, but we don't do a RelVal every time we tag AliDPG, so not every AliDPG tag is checked...

Chiara

**Pull request merged**
