### PR TITLE
Add RSN003 configuration(add Sigma1385 and cc)

### PR DESCRIPTION
**Pull request by BongHwi**
RSN003 is coped from RSN002
but just sigma1385 is just added.

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @BongHwi, all,

if you agree I would wait with merging this PR until we understand the problem with the Rsn002 macros (see discussion in RSN meeting of 3rd July 2019).

Cheers,
Michael

**Comment by BongHwi** [comment]
@miweberSMI Sure, Let's merge it together after we solve the issue.

Regards,
Bong-Hwi

**Comment by miweberSMI** [comment]
Hi @BongHwi,

there is a fix: [https://github.com/alisw/AliRoot/pull/973](https://github.com/alisw/AliRoot/pull/973).
I will wait for this PR to be merged to AliRoot master and then test this macro as well...

Cheers,
Michael

**Comment by BongHwi** [comment]
@miweberSMI Okay, thanks for updating me.

Regards,
Bong-Hwi

**Comment by miweberSMI** [comment]
Hi @BongHwi,

the PR is merged and I started the test of this macro. Meanwhile, could you check with LF conveners if they agree with this new generator macro (ideally they could comment here on the PR).
Especially since this macro is basically the same as 002 but with an extension.

Thanks and cheers,
Michael

**Comment by miweberSMI** [comment]
Hi again,

I tested the macro and it works (also the fix alisw/AliRoot#973) is curing the issue with missing decay daughters that was reported in ALIROOT-7708.

Cheers,
Michael

**Comment by BongHwi** [comment]
Hi @miweberSMI ,

Good, I wrote a request to conveners to check if this is okay to commit for new RSN injected generator.
In any case, we'll have a meeting this afternoon, I'll talk at the meeting.

Regards,
Bong-Hwi

**Comment by BongHwi** [comment]
K(1430)0 and K(1430)+ are added.

**Comment by miweberSMI** [comment]
Dear all,

I tested the updated macro and it doesn't show any problems with running (I did not check the results). Once I get green light from conveners, I will merge the PR.

Cheers,
Michael

**Comment by miweberSMI** [comment]
Dear all,

I tested again the updated macro (now named 002) and it still doesn't show any problems with running (I did not check the results). Once I get green light from conveners, I will merge the PR.

Cheers,
Michael

**Comment by efragiac** [comment]
Dear Michael,
the macro is fine for us. It contains the two additional resonances (Sigma(1385) and K*(1430)) that we need. It is fine to overwrite the old macro (Rsn002).
Cheers,
Enrico

**Comment by miweberSMI** [comment]
Dear @efragiac,

thanks for confirmation. I am merging to the master then.

Cheers,
Michael

**Pull request merged**
