### PR TITLE
Take coreFlukaVmc.inp from AliRoot

### PR DESCRIPTION
**Pull request by dberzano**
Requires alisw/AliRoot#783

### CODE REVIEW

**Comment by dberzano** [comment]
@chiarazampolli please merge at your convenience

**Comment by dberzano** [comment]
The corresponding AliRoot PR has been merged. If we merge this, we should note that we can use only AliRoot versions from v5-09-38 on for Monte Carlo. Anyway, the linked ticket [ALIROOT-7991](https://alice.its.cern.ch/jira/browse/ALIROOT-7991) has only this point pending before closing it.

**Comment by chiarazampolli** [comment]
Ciao @dberzano ,

Cannot we make a check, if the file exists in AliRoot, take it from there, otherwise from FLUKAVMC?

Cheers,

Chiara

**Comment by dberzano** [comment]
Hi @chiarazampolli, the new version takes the file from AliRoot and falls back on FLUKA. It also spits out clear error messages in case one or more of the required files could not be found. IMHO this should be actually made a _fatal_ error and the simulation should stop right away.

**Comment by dberzano** [comment]
(p.s. I have tested it and it works)

**Comment by chiarazampolli** [comment]
Ciao @dberzano ,
My bad, I overlooked the changed, and did not see the fall back. 
But I agree, if one file is not found, the simulation should be aborted. Will you do the changes?
Cheers,
Chiara

**Comment by dberzano** [comment]
No, no, the change was not there; following your suggestion, I have added it 😄 I can add the other requested changes as well, hold on.

**Comment by dberzano** [comment]
Done, please have a look.

**Comment by chiarazampolli** [comment]
Perfect, I will merge it now.

Chiara

**Pull request merged**
