### PR TITLE
ALIROOT-7077: ADD setup for the TPC ion tail and crosstalk simulation

### PR DESCRIPTION
**Pull request by miranov25**
* Enabling TPC Hits->SDigits->Digits
  * current default for TPC is Hits->Digits
* adding void to the function invocation (Optional?)
  * correct C
  * otherwise my editor was highlighting large faction of code as syntax error

### CODE REVIEW

**Comment by miranov25** [comment]
Hallo Francesco and Roberto.

I added new configuration of the AliDPG macros - to enable Crosstalk and IonTail simulation.
I would like to review the code before actual pulling.
To consider:
* I did not run test yet - I wanted to ask before if the modication is according your schema
* I modified function invocation adding void

**Comment by fprino** [comment]
Hi Marian,

I have a doubt on the way one should call SetMakeSDigits.
Shouldn't one do:

```
sim.SetMakeSDigits("TPC TRD TOF PHOS HMPID EMCAL MUON ZDC PMD T0 VZERO FMD AD");
sim.SetMakeDigitsFromHits("ITS");
```

instead of just
`
sim.SetMakeSDigits("TPC");
`

Cheers, Francesco

**Comment by miranov25** [comment]
hallo Francesco.
Thanks for checking.
You are right.  I will make modification and run the test.
I expect to run small test in the evening.
I will let you know.
Maria

**Comment by miranov25** [comment]
For the record. Our old sim.C which we used for the ion tail/crosstalk simulation productions 2 years ago at GSI:
https://github.com/alisw/AliRoot/blob/master/test/testdEdx/sim.C
```
simulator.SetMakeSDigits("ITS TPC TRD TOF PHOS HMPID EMCAL MUON FMD ZDC PMD T0");
  //simulator.SetMakeDigitsFromHits( "ITS TPC");
```

**Comment by fprino** [comment]
Hi Marian,

thanks a lot!
For me the code is OK to be merged in the master branch.
@miweberSMI and @preghenella, do you agree?

Cheers, Francesco

**Comment by miweberSMI** [comment]
Hi Marian, all,

sorry for looking just now at the code. I am fine with the changes, please go ahead!

Cheers,
Michael

**Comment by fprino** [comment]
Thank you! The request is now merged in the master.
I will port it to the relevant release branches.
We will need a new AliDPG tag at the moment of re-running the productions.

**Comment by miranov25** [comment]
Thank you

**Pull request merged**
