### PR TITLE
Configuration of weak decay finder for PbPb (from Livio)

### PR DESCRIPTION
**Pull request by fprino**

### CODE REVIEW

**Comment by fprino** [comment]
Hi @bianchil, @ddobrigk,

this is the modification of the AOD filtering macro  to re-run the WD finder in the filtering.
Please let me know if you see something wrong.

Ciao, Francesco

**Comment by fprino** [comment]
Hi,

following a remark from David I added the method to enable the invariant mass window cut for the Pb-Pb case

Cheers, Francesco

**Comment by ddobrigk** [comment]
Ciao, thanks, this looks reasonable to me (as far as I can tell :-) )

**Comment by bianchil** [comment]
Hello, sorry for the delay. Yes, good for me!

**Pull request merged**
