### PR TITLE
Add basic shell syntax test

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @dberzano, @fprino,

I was wondering about this pull request and why it was never merged?

Thanks and cheers,
Michael

**Comment by dberzano** [comment]
We can discuss it when I am back from vacation if you want. At the moment it's incomplete. What I would like to do is:

- [ ] Add Travis CI in order to run it automatically
- [ ] Prevent merging of PRs that don't pass the test
- [ ] Check only changed files

I find this static shell check quite useful to prevent common ambiguities (I would not say "mistakes" as shell scripting is not a real programming language...)

**Comment by miweberSMI** [comment]
Hi Dario,
Thanks for clarification, I was just wondering.

**Comment by ktf** [comment]
Can we either converge on this or close it, please?

**Comment by miweberSMI** [comment]
Hi @ktf and @dberzano,

what should we actually do with this PR?

Thanks and cheers,
Michael

**Comment by ktf** [comment]
Given it has been idle for almost two years, I would close this. I also would recommend to avoid any kind of bashism and make sure scripts adhere to the well documented [POSIX standard](https://pubs.opengroup.org/onlinepubs/009695399/utilities/sh.html) for `/bin/sh`, but that's my 2 cents.

**Comment by miweberSMI** [comment]
Hi @ktf 

thanks for confirmation, any input from @dberzano?

Thanks and cheers,
Michael

**Comment by chiarazampolli** [comment]
Closing, we did not follow up...

**Pull request closed without merging**
