### PR TITLE
update generation macros for MC Pb-Pb 2018 (pass2)

### PR DESCRIPTION
**Pull request by ffionda**
Changes include: 
- update of prompt jpsi pt-spectra (from Pb-Pb 2018 data)
- EvtGen usage for B->J/psi+X decays

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello,

Looks ok to me. @gconesab , @fprino , do you agree?
@ffionda , is this needed for some MC? Sorry if I missed it in some JIRA.
Chiara

**Comment by ffionda** [comment]
Dear Chiara.
thank you for your feedback. This update is needed for Pb-Pb pass2 productions with injected Jpsi. 
The corresponding JIRA ticket of pass1 production is https://alice.its.cern.ch/jira/browse/ALIROOT-8251 
Regards,

Fiorella

**Comment by chiarazampolli** [comment]
Hello Fiorella,
Thanks! So this is not for now for a planned MC, right? Just to be sure I did not miss any discussion on new developments. 

Chiara

**Comment by ffionda** [comment]
Ciao Chiara,
yes, you are right, there is no pass2 request for this production so far. The DQ conveners will make the request at the PB, but this is planned after the general purpose production (pass2) will start. We are proposing these changes in advance in order to have everything already in place when the production will be requested.  
Thank you,
Fiorella

**Comment by miweberSMI** [comment]
Hi @chiarazampolli , all,

so far this was not requested, because we were expecting some organized call for PWG productions to be redone for pass 2. This macro is in preparation for one of those productions. 
Should we request this individually, or there will be some table with productions to be reproduced (we can discuss this also elsewhere)?

Cheers,
Michael

**Comment by chiarazampolli** [comment]
Ciao @miweberSMI , 

@gconesab will start collecting the information on MCs to be redone for pass2 next week. I was asking whether there was a request because I was not aware of the needs for this development, and it could have been that I was just missing it. Usually PR in AliDPG are done following discussions, so that we know in which context they are made. This is all, no problem if for now we won't use this new functionality. Now we know what it is needed for :-)

Since it looks fine, I will merge it now (@fprino , @gconesab , please, let me know in case you see any issue).

Chiara

**Pull request merged**
