### PR TITLE
Add ITS track QA task instance for MB triggers

### PR DESCRIPTION
**Pull request by fprino**

### CODE REVIEW

**Comment by fprino** [comment]
Hi @chiarazampolli,

it seems you have to merge this commit: for me the button rebase and merge is grey and not "pushable".

Ciao, Francesco

**Comment by chiarazampolli** [comment]
Hello, 

The PR is fine for me!

Chiara

PS. probably since I didn't add any comment but my review was requested, one could not merge it (at least I could not merge it, as Fraccesco).

**Comment by chiarazampolli** [comment]
Hello,
I reviewed and approved, but the merging button is still grey. I don't know if it is a matter of time... Maybe @dberzano  knows?

Chiara

**Comment by chiarazampolli** [comment]
It says: 
WIP Expected — Waiting for status to be reported 
But this is not "WIP"... 

Chiara

**Comment by dberzano** [comment]
Must be a bug of the WIP plugin, which I have now disabled.

**Comment by chiarazampolli** [comment]
Ciao, 

Ok, now it worked. 
Other PR were working, what did this have special? We requested reviews other times... 

Chiara

**Pull request merged**
