### PR TITLE
Add Ds option to Hijing HF001 custom generator

### PR DESCRIPTION
**Pull request by fcatalan92**

### CODE REVIEW

**Comment by fprino** [comment]
Hi,

for Michael, Chiara and Catlin: this modification is needed for a production that HF may need in the next weeks for the Pb-Pb 2018 analysis.
If you agree, I would merge it in AliDPG.

Cheers, Francesco

**Comment by miweberSMI** [comment]
Hi @fprino,

as far as I can tell, it looks OK, but I guess you have tested the functioning...

Cheers,
Michael

**Comment by chiarazampolli** [comment]
Ciao,

For me it is also fine, if someone tested it, like Michael said :-)
Do we have green light also from @agrelli and @xcheung?

Chiara

**Comment by fprino** [comment]
Hi,

I confirm that Fabio tested it before opening the PR.
Ciao, Francesco

**Comment by agrelli** [comment]
Ciao

good to go from my side

Alessandro

**Comment by chiarazampolli** [comment]
Thanks to both Francesco and Alessandro, let's merge!

Chiara

**Pull request merged**
