### PR TITLE
emove the Omega_C production and enlarge the eta range of the trigger particle

### PR DESCRIPTION
**Pull request by gluparel**
Dear all,
according to what discussed in this ticket https://alice.its.cern.ch/jira/browse/ALIROOT-8281, I have to remove the Omega_C production and enlarge the eta range of the trigger particle.

Is this possible? I see a message that the commit "Can't automatically merge"... is this due to some mistake I have done at a certain point with my branch? Do I need to fix this or the pulling ot the master can be done in any case?

Thanks
Cheers
Grazia

### CODE REVIEW

**Comment by gconesab** [comment]
Ciao Grazia,

it seems as if you want to commit again the changes of commit #335?
Have you done git --pull rebase before doing your last changes and new request?

Cheers ... Gustavo

**Comment by gluparel** [comment]
Hi Gustavo,

yes, I have done git pull --rebase before the last changes, but I ended up in this situation :)
Probably for something that I have done before.

What I would like to pull, is this:
https://github.com/alisw/AliDPG/pull/335/commits/0fc369660d4d84c3ad7cee9b223b2970c5ba6b7b

Do you have any suggestion?
Sorry for the mess
Cheers
Grazia

**Comment by gconesab** [comment]
Sincerely, no idea, I  would maybe close and restart from scratch?

**Comment by gluparel** [comment]
Yes, I close this one and restart.

Grazia

**Pull request closed without merging**
