### PR TITLE
small update to decay B hadrons (->J/psi) by EvtGen

### PR DESCRIPTION
**Pull request by ffionda**

### CODE REVIEW

**Comment by miweberSMI** [comment]
Ciao @ffionda, all,

thanks for this PR, could I ask you for which production this is needed (JIRA ticket if available)?
I am not expert on the JPsi etc. but would this change affect also other possible productions? And if so, why not adding a new option to enable this different decay? Or was it wrong in the first place and needs to be fixed.

Thanks for explanation and cheers,
Michael

**Comment by chiarazampolli** [comment]
Hello, 
I agree with the doubts by Michael... 

Chiara

**Comment by chiarazampolli** [comment]
PS: this does not look like a "small" change as in the PR title, but I might be wrong.

**Comment by fprino** [comment]
Hi,

the change is in the method Generator_Jpsiee, so I guess that it will affect the PWG specific productions that call this generator, which are these ones in PWGDQ:
CustomGenerators/PWGDQ/EPOS_Jpsiee002.C
CustomGenerators/PWGDQ/Hijing_Jpsiee001.C
CustomGenerators/PWGDQ/EPOS_Jpsiee_pPb8TeV.C
CustomGenerators/PWGDQ/Pythia6_Perugia2011_Jpsiee001.C
CustomGenerators/PWGDQ/Hijing_JpsieeXeXe.C
CustomGenerators/PWGDQ/Pythia6_Perugia2011_Jpsi2ee13TeV.C
CustomGenerators/PWGDQ/Pythia6_Perugia2011_Jpsi2ee5TeV_2017.C
CustomGenerators/DPG/Validation_pp001.C

On the changes: I saw that some decay options were changed, and I guess the reason is to have all HF particle species decayed by EvtGen.

The removal of these lines:
pythia->SetCutOnChild(1);
pythia->SetPdgCodeParticleforAcceptanceCut(443);
pythia->SetChildYRange(-2, 2);
pythia->SetChildPtRange(0, 10000.);
is also needed (if I got it right) because now the beuty hadrons are decayed by EvtGen after the PYTHIA event gemeration and therefore we cannot require any more the presence of a J/psi in the stack to accept the event.

Cheers, Francesco

**Comment by ffionda** [comment]
Dear Michael, Francesco, Chiara
(adding in cc also Ionut and Markus)
These changes are needed for the J/psi production (in particular for the non-prompt J/psi part) anchored to Pb-Pb 2018 
(the corresponding custom generator is AliDPG/MC/CustomGenerators/PWGDQ/Hijing_Jpsiee001.C). The JIRA ticket for this production
doesn't exist yet.

The reason for introducing these changes was explained very well by Francesco in the answer below. 
In particular in the old method beauty hadrons were decayed by Pythia (and only J/psi -> ee were decayed by EvtGen+PHOTOS) 
and the conditions for accepting events was based on J/psi daughters acceptance. 
Now beauty hadrons are left undecayed in Pythia (so we should remove the conditions on the daughters otherwise 
all events would be rejected) and they are decayed by EvtGen afterwards. 
As mentioned also by Francesco all HF particles are now switched off and decayed by EvtGen (i.e. both prompt J/psi and B hadrons) ,
so "gene->SetParticleSwitchedOff(AliGenEvtGen::kCharmPart)" was replaced by
"gene->SetParticleSwitchedOff(AliGenEvtGen::kHFPart)"

These changes will affect also other productions as mentioned by Francesco and Michael, so if you think it's better
we could also add another option in the method Generator_Jpsiee.C to enable it. 

Thank you,
Regards

Fiorella
________________________________________

**Comment by fprino** [comment]
Hi Fiorella,

the idea of adding an option looks a good one to me.
With your commit, we will have an improvement of our simulations of the B decays because we to move to EvtGen which is generally considered a better decayer for HF particles w.r.t. Pythia.
So, from this point of view, it would make sense that all the generator-configuration macros profit of this feature.
However, this will cause a change in the simulation output w.r.t. previous productions done with the Pythia decayer.
In this sense, the option could turn out to be useful.

We are going to tag this morning.
Let me know if you need urgently your new feature and if you can manage to implement it by today.
In such case, we can wait for you.
Otherwise, we would tag now and then we can create a new tag next week to include your commit.

Cheers, Francesco

**Comment by ffionda** [comment]
Dear Francesco,
yes, you are right about EvtGen. 
We don't need urgently this feature (the JIRA ticket will be created later next week), so you can go ahead with 
the tagging without waiting for me. Then we can commit these changes (including the option for selecting the
decay mode for B-hadrons) next week.
Thank you,
Regards

Fiorella 
________________________________________

**Comment by miweberSMI** [comment]
Dear @ffionda,

looks good to me now, what do others (@chiarazampolli, @fprino) think? 
@ffionda, is there already a JIRA ticket for a production that needs this PR?

Thanks and cheers,
Michael

**Comment by fprino** [comment]
Hi,

also to me it seems OK.
Thanks Fiorella!

Ciao, Francesco

**Comment by ffionda** [comment]
Dear Michael, 
Markus (in cc)  will open soon the corresponding Jira ticket.
Thank you
Regards,

Fiorella
________________________________________

**Comment by ffionda** [comment]
dear all,

I created the JIRA ticket for the PbPb central barrel production for 
PbPb 2018 (LHC18q,r) https://alice.its.cern.ch/jira/browse/ALIROOT-8251

regards,
Markus

**Comment by chiarazampolli** [comment]
Looks ok to me too. 

Chiara

**Comment by miweberSMI** [comment]
Dear @ffionda, @mkkohler, all,

I am merging this PR to the master now. We are still waiting for one more PR from LF and will then ask for a new tag (probably next week).

Cheers,
Michael

**Pull request merged**
