### PR TITLE
Added custom generator for Run3 MC production HIJING + QED + Nuclei

### PR DESCRIPTION
**Pull request by fbellini**

### CODE REVIEW

**Comment by miweberSMI** [comment]
Dear Francesca,

sorry for not replying in the last days. I will try to test it as soon as possible. At the moment, we are still debugging the plain Hijing simulation, so there is no rush here...

Cheers,
Michael

**Comment by miweberSMI** [comment]
Dear Francesca, all,

I checked the simulation and reconstruction stage and it seems to work (at least with a recent aliroot/physics) locally. A crash happens in the check ESD stage, which is probably related to the issues reported in ALIROOT-7743. We shoudl understand this before moving on here.

Cheers,
Michael

**Comment by fbellini** [comment]
Hi Michael, all,
   thanks for running the checks. We will then stand by until the issue in ALIROOT-7743 is solved. After that, please let me know if any further action or test is needed from my side.
Thank you and best regards,

Francesca

**Comment by miweberSMI** [comment]
Hi Francesca,

I am merging this PR now and port to the production branch. It seems the problems are not related to generators.

Cheers,
Michael

**Pull request merged**
