### PR TITLE
removed mixed mode (from sh script only)

### PR DESCRIPTION
**Pull request by miweberSMI**

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @chiarazampolli , @fprino , @shahor02,

for safety, I removed the mixed mode from the dpg script. Could you have a look? 
At the moment I am keeping the option in the macros, or should we remove it completely? What do you think?

Cheers,
Michael

**Comment by shahor02** [comment]
Hi @miweberSMI 

I think suppressing it only in the macro is enough, I would keep it in the macro in case somebody will need to study the crosstalk between the clusters/tracks of underlying and embedded events.

Cheers,
 Ruben

**Comment by chiarazampolli** [comment]
Hello,
I agree with @shahor02 , let's remove it from the script, but leave it in the macro. 
Thanks!
Chiara

**Comment by miweberSMI** [comment]
OK, thx. Then I am merging now...

**Pull request merged**
