### PR TITLE
DPMJET f0 and f2 injected pPb5TeV

### PR DESCRIPTION
**Pull request by ekryshen**
By request from Viktor Riabov

### CODE REVIEW

**Comment by vriabov** [comment]
The request is related to JIRA ticket:
https://alice.its.cern.ch/jira/browse/ALIROOT-7633?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=208069#comment-208069

**Comment by miweberSMI** [comment]
Hi Viktor,

thanks for the pull request. I tested it and it is working fine. Before merging and porting to the production branches, I would like the conveners to comment. Especially o the macro naming, since we have a similar one (with quite different structure and resonances) here:
https://github.com/alisw/AliDPG/blob/master/MC/CustomGenerators/PWGLF/DPMJET_RsnInject_pPb8TeV.C

Cheers,
Michael

**Comment by fbellini** [comment]
Hello Michael, Victor,
    thanks for preparing the macro. 
The generator is ok and it is indeed different wrt the generator for the p-Pb 8 TeV, as the injection is done flat in pT contrary to there. It is done similarly to what done in past productions with hijing and pythia. 

About the naming, I would stick to the convention <generator>_<rsn>_<system><number>, e.g. "Dpmjet_Rsn_pPb001.C". I would not specify the energy in the macro name, because there is nothing specific of a given energy in the configuration. In this way, we can have several generators ready to be used with different energies. The system is instead informative, because the rapidity range is set accordingly.

We then give green light to port this macro in AliDPG. Can you please take care of changing the name though?

Thank you and cheers,
   Alexander and Francesca

**Comment by miweberSMI** [comment]
Hi Francesca,

thanks for the comment and approval. I merged it to the AliDPG master, and will change the name of this (and the other macro accordingly).

Cheers,
Michael

**Pull request merged**
