### PR TITLE
[ALIROOT-8487] EPOS pileup generator for bkg in embedding MCs

### PR DESCRIPTION
**Pull request by chiarazampolli**
Removing also "&" when generating EPOS event in fifo

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @catalinristea , 

This is how I ran it:

./dpgsim.sh --run 266296 --mode full --uid 1 --nevents 100 --keepTrackRefsFract
ion 10 --generator EPOSLHC --background DPG:EPOS_Pileup_bkg --nbkg 1 --simulatio
n SimulationDefaultIonTail --detector NoZDC

I will add a comment in JIRA (ALIROOT-8487).

Chiara

**Comment by catalinristea** [comment]
Ciao Chiara,

To me looks good, compared to the other generators with embedding and pileup. Maybe Gustavo and(or) Francesco can also confirm before merging. Thanks!

Yours,
Catalin.

**Comment by gconesab** [comment]
Hello, it looks good to me ... Gustavo

**Comment by fprino** [comment]
Hi,

thanks! Also to me it looks OK.
I am merging it.

Ciao, Francesco

**Comment by chiarazampolli** [comment]
Hello,

Thanks! I will then make a new tag.

Chiara

**Pull request merged**
