### PR TITLE
ALIROOT-8507 Make the nuclex Pb-Pb gen pileup ready

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by gconesab** [comment]
Ciao @mpuccio 
I tried your macro and it is not working, even commenting out the pile-up part, can you check?

**Comment by gconesab** [comment]
I tried the original version of the macro on lxplus [AliPhysics/v5-09-54c-01-1 AliDPG/prod-202006-03-1]

$ALIDPG_ROOT/bin/aliroot_dpgsim.sh --run 296196 --mode sim --simulation GeneratorOnly --uid 1 --nevents 2 --generator PWGLF:Hijing_Nuclex004 --bmin 0 --bmax 5

and unless I am doing something wrong, it crashes here:
#6  0x00007f2a8e535059 in AliGenBox::GenerateN (this=0x103268b0, ntimes=<optimized out>) at /jenkins/workspace/build-any-ib/sw/20156149/1/SOURCES/AliRoot/v5-09-54c/v5-09-54c/EVGEN/AliGenBox.cxx:108

**Comment by mpuccio** [comment]
Hi,

on lxplus, using AliPhysics/vAN-20200730-1 + AliDPG master I run:

```
ALIDPG_ROOT=/afs/cern.ch/user/m/mpuccio/AliDPG ~/AliDPG/MC/dpgsim.sh --mode sim --run 258537 --generator PWGLF:Hijing_Nuclex004 --uid 8 --nevents 1 --ocdb cvmfs
```

(as well as the pileup version) and everything work for me.
Cheers,
Max

**Comment by mpuccio** [comment]
Ah I see you are using GeneratorOnly: this was not working sometimes ago for cocktail generators. Not sure if the issue was solved, but I never try the generator with that option as we do not need it.

**Comment by gconesab** [comment]
Sorry, I forgot to remove the GeneratorOnly option, but I did not. Testing now, if ok, I will merge. Thanks and sorry for the noise!

**Pull request merged**
