### PR TITLE
LoadLibraries is not needed

### PR DESCRIPTION
**Pull request by chiarazampolli**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @shahor02,

I removed the "LoadLibraries" call also from the TPC SP calibration part. I tested it, and everything works, in the sense that the processing was successful - I did not check the results. Do you agree to merge it?

Cheers,

Chiara

**Comment by fprino** [comment]
HI Chiara, all,

fine with me.

Francesco

**Comment by chiarazampolli** [comment]
Many thanks to both Francesco and Ruben, merging now.

BTW, should I remove completely the macro? Now it is used nowhere.

Chiara

**Comment by shahor02** [comment]
I would keep it for the moment.
Cheers,
 Ruben

**Comment by chiarazampolli** [comment]
Ok, I thought the same, and then was doubtful as one can always recover it from git.

Merging like this now.

Chiara

**Pull request merged**
