### PR TITLE
Added Omega decays and cross section info

### PR DESCRIPTION
**Pull request by ekryshen**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Looks fine to me. @gconesab , @fprino , any comment?

Chiara

**Comment by fprino** [comment]
I am not at all an expert of Starlight. From what I could see in the code, the modifications look OK to me.
Francesco

**Comment by chiarazampolli** [comment]
Yes, the same caveat holds for me, I rely on the settings by Evegny :-)

**Comment by gconesab** [comment]
Hi, changes look fine also to me, merging.

**Pull request merged**
