### PR TITLE
Resonance + Nuclei injection scheme

### PR DESCRIPTION
**Pull request by mpuccio**
Hi @miweberSMI ,

this configuration will be needed for an upcoming production request by PWGLF.
We still need to put some new states that are not present in the current AliRoot release, thus expect an update on this!

Thanks and cheers!
Max

### CODE REVIEW

**Comment by miweberSMI** [comment]
Thanks @mpuccio 
I will test it and approve it in case the test is succesful (but only then).

Cheers,
Michael

**Comment by miweberSMI** [comment]
Hi @mpuccio 

I tested it and it is running fine.
Thanks for preparing this nice generator macro!

Cheers,
Michael

**Comment by miweberSMI** [comment]
Hi again @mpuccio,

I ported the commit also to the production branches for v5-08-XX and v5-09-XX, so as soon as we have a new tag, you should be able to test it on the GRID. 

Have a good night,
Michael

**Comment by mpuccio** [comment]
Thanks a lot!

**Comment by miweberSMI** [comment]
You are welcome!

**Pull request merged**
