### PR TITLE
Add generator for absorption studies

### PR DESCRIPTION
**Pull request by mpuccio**
This new generator will be needed for an upcoming MC request.

@mcolocci please check the pt ranges of the generators

### CODE REVIEW

**Comment by mcolocci** [comment]
> 
> 
> This new generator will be needed for an upcoming MC request.
> 
> @mcolocci please check the pt ranges of the generators

Many thanks @mpuccio for doing this.
Fine with p = [0.5, 3] GeV/c for (anti)tritons.
Instead I would go lower for He-3.
That is, I would choose p = [1, 10] GeV/c for He-3.
If we go a bit higher in momentum is also fine.
Many thanks again.

**Comment by mpuccio** [comment]
Ciao Manuel,
but don't we have a cut at 3 GeV/c minimum for He3? I put 2GeV/c for safety, but I am not sure what do we gain going lower.
Cheers,
Max

**Comment by mcolocci** [comment]
Yes. However by using the pass3 (not the special reconstruction) we can go lower in momentum.
Then, we will need to cut "offline" at 3 cm in TOF (in the MC as well).
We saw indeed that there is no large extra signal out of that.

**Comment by mpuccio** [comment]
OK, updated! I will open the ticket this evening

**Pull request merged**
